version: '2'
services:
  api:
    tty: true
    stdin_open: true
    build:
      context: .
      args:
        RAILS_ENV: production
    command: |
      ./wait-for-it.sh postgres:5432 -- bash -c "bundle exec rake db:migrate && bundle exec puma -p 5000"
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgres://root:password@postgres:5432/anna_speak
      - RAILS_LOG_TO_STDOUT=true
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=anna_speak
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432"
  redis:
    image: redis
    hostname: redis
    command: redis-server
    volumes:
      - /var/lib/redis/data
  sidekiq:
    depends_on:
      - redis
      - postgres

    links:
      - redis
      - postgres
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://root:password@postgres:5432/anna_speak
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/app'
    env_file:
      - .env